package fr.iglee42.resourcefulshulkers;


import net.neoforged.neoforge.common.ModConfigSpec;

public class ResourcefulShulkersConfig {
    public static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();
    public static final ModConfigSpec SPEC;

    public static final ModConfigSpec.ConfigValue<Integer> ABSORBER_AURA;
    public static final ModConfigSpec.ConfigValue<Boolean> TIAB_PROTECTION;
    public static final ModConfigSpec.ConfigValue<Boolean> GENERATE_RECIPES;
    public static final ModConfigSpec.ConfigValue<Integer> NO_AI_AURA;
    public static final ModConfigSpec.ConfigValue<Integer> BASE_GENERATION;
    public static final ModConfigSpec.ConfigValue<Integer> QUANTITY_UPGRADE_MODIFIER;
    public static final ModConfigSpec.ConfigValue<Integer> BASE_SHELL;
    public static final ModConfigSpec.ConfigValue<Double> SHELL_UPGRADE_MODIFIER;

    static {
        BUILDER.push("ResourcefulShulker Config");

        ABSORBER_AURA = BUILDER.comment(" The total of aura given by absorber with one shulker. Prefer to have a multiple of 32").defineInRange("absorber_aura", 4096,0,Integer.MAX_VALUE);
        TIAB_PROTECTION = BUILDER.comment(" Enable the protection of Generating Box against time in a bottle").define("tiab_protection", true);
        GENERATE_RECIPES = BUILDER.comment(" Enable the auto generation of recipes for custom shulkers").define("generate_recipes", true);
        NO_AI_AURA = BUILDER.comment(" The amount of aura required to keep entity on infuser without AI").defineInRange("no_ai_aura", 100,0,Integer.MAX_VALUE);
        BASE_GENERATION = BUILDER.comment(" The base amount of items generated by a box. Amount is calculated with: base + (nb_upgrades * modifier)").defineInRange("base_generation_amount", 1,0,64);
        QUANTITY_UPGRADE_MODIFIER = BUILDER.comment(" The modifier for each quantity upgrade").defineInRange("quantity_upgrade_modifier", 2,0,Integer.MAX_VALUE);
        BASE_SHELL = BUILDER.comment(" The base amount of durability restored by a shulker shell. Amount is calculated with: base * (nb_upgrades * modifier)"," Warning: The shell is consumed only if the box is missing at least the amount of durability restored by the shell").defineInRange("base_shell_durability", 4,0,64);
        SHELL_UPGRADE_MODIFIER = BUILDER.comment(" The modifier for each shell upgrade").defineInRange("shell_upgrade_modifier", 0.5,0,Double.MAX_VALUE);

        BUILDER.pop();
        SPEC = BUILDER.build();
    }

    public static class Client {
        public static final ModConfigSpec.Builder BUILDER = new ModConfigSpec.Builder();
        public static final ModConfigSpec SPEC;

        public static final ModConfigSpec.ConfigValue<Integer> AURA_BAR_X;
        public static final ModConfigSpec.ConfigValue<Integer> AURA_BAR_Y;

        static {
            BUILDER.push("ResourcefulShulker Client Config");

            AURA_BAR_X = BUILDER.comment(" The x position of the aura bar, it is based on the right of the screen , so it's screenWidth - auraBarX").defineInRange("aura_bar_x", 24,0,Integer.MAX_VALUE);
            AURA_BAR_Y = BUILDER.comment(" The y position of the aura bar").defineInRange("aura_bar_y", 0,0,Integer.MAX_VALUE);

            BUILDER.pop();
            SPEC = BUILDER.build();
        }
    }
}