import dev.ithundxr.silk.ChangelogText

buildscript {
    repositories {
        maven { url = 'https://repo.spongepowered.org/repository/maven-public/' }
        mavenCentral()
    }
    dependencies {
        classpath 'org.spongepowered:mixingradle:0.7-SNAPSHOT'
    }
}

plugins {
    id 'idea'
    id 'java-library'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
    id 'dev.ithundxr.silk' version '0.11.15'
    id 'me.modmuss50.mod-publish-plugin' version '1.1.0'
}

apply plugin: 'org.spongepowered.mixin'

group = mod_group_id
version = minecraft_version + "-" +mod_version

String gitHash = calculateGitHash()
String changelogText = ChangelogText.getChangelogText(project).toString()

base {
    archivesName = mod_name
}

java.toolchain.languageVersion = JavaLanguageVersion.of(17)


minecraft {
    mappings channel: 'official', version: minecraft_version

    accessTransformers = project.files("src/main/resources/META-INF/accesstransformer.cfg")

    runs {
        client {
            workingDirectory project.file('run')
        }

        server {
            workingDirectory project.file('run-server')
            args 'nogui'
        }

        gameTestServer {
            workingDirectory project.file('run')
        }

        data {
            workingDirectory project.file('run')

            args '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }


        configureEach {
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            property 'forge.enabledGameTestNamespaces', project.mod_id
            property 'mixin.env.remapRefMap', 'true'
            property 'mixin.env.refMapRemappingFile', "${projectDir}/build/createSrgToMcp/output.srg"
            mods {
                "${mod_id}" {
                    source sourceSets.main
                }
            }
        }
    }

}

sourceSets.main.resources { srcDir 'src/generated/resources' }

mixin {
    add sourceSets.main, "${mod_id}.refmap.json"

    config "${mod_id}.mixins.json"
}

repositories {

    flatDir {
        dir 'libs'
    }


    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
    }

    maven {
        name "igleeRepoReleases"
        url "https://maven.iglee.fr/releases"
    }
    maven {
        url "https://cursemaven.com"
        content {
            includeGroup "curse.maven"
        }
    }

}

dependencies {

    minecraft "net.minecraftforge:forge:${minecraft_version}-${forge_version}"

    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}")
    compileOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge-api:${jei_version}")
    runtimeOnly fg.deobf("mezz.jei:jei-${minecraft_version}-forge:${jei_version}")

    implementation fg.deobf("fr.iglee42:IgleeLib:${minecraft_version}-${lib_version}")

    //runtimeOnly "curse.maven:atlasviewer-633577:6088094"
    //runtimeOnly "curse.maven:configured-457570:7276577"

    //implementation "curse.maven:just-dire-things-1002348:7463040"
    compileOnly "curse.maven:gag-694962:6120294"
    implementation fg.deobf("curse.maven:time-in-a-bottle-895919:4744787")

    compileOnly(annotationProcessor("io.github.llamalad7:mixinextras-common:0.5.5"))
    implementation(jarJar("io.github.llamalad7:mixinextras-forge:0.5.5")) {
        jarJar.ranged(it, "[0.5.5,)")
    }

    annotationProcessor 'org.spongepowered:mixin:0.8.5:processor'
}

var generateModMetadata = tasks.register("generateModMetadata", ProcessResources) {
    var replaceProperties = [
            minecraft_version      : minecraft_version,
            minecraft_version_range: minecraft_version_range,
            forge_version          : forge_version,
            forge_version_range    : forge_version_range,
            loader_version_range   : loader_version_range,
            mod_id                 : mod_id,
            mod_name               : mod_name,
            mod_license            : mod_license,
            mod_version            : mod_version,
            mod_authors            : mod_authors,
            mod_description        : mod_description,
            lib_version: lib_version,
            lib_version_range: lib_version_range
    ]
    inputs.properties replaceProperties
    expand replaceProperties
    from "src/main/templates"
    into "build/generated/sources/modMetadata"
}

sourceSets.main.resources.srcDir generateModMetadata

jar.finalizedBy('reobfJar')

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

publishMods {
    file = tasks.jar.archiveFile
    displayName = "$mod_name $mod_version for mc$minecraft_version"
    version = project.version
    changelog = changelogText
    type = STABLE
    modLoaders.add("forge")
    dryRun = providers.environmentVariable("DRY_RUN").map { it == "true" }.orElse(false).get()

    def modrinthProjectId = providers.gradleProperty("publish_modrinth_project_id").orNull
    if (modrinthProjectId) {
        modrinth {
            accessToken = providers.environmentVariable("MODRINTH_TOKEN")
            projectId = modrinthProjectId
            minecraftVersions.add(minecraft_version)
        }
    }

    def curseforgeProjectId = providers.gradleProperty("publish_curseforge_project_id").orNull
    if (curseforgeProjectId) {
        curseforge {
            accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
            projectId = curseforgeProjectId
            projectSlug = providers.gradleProperty("publish_curseforge_project_slug").orNull
            minecraftVersions.add(minecraft_version)
            changelogType = "markdown"
            clientRequired = true
            serverRequired = true
        }
    }

    def githubRepository = providers.gradleProperty("publish_github_repository").orNull
    if (githubRepository) {
        github {
            accessToken = providers.environmentVariable("GITHUB_TOKEN")
            repository = githubRepository
            commitish = gitHash
            tagName = "$mod_version-$minecraft_version"
            file.unset()
            file.unsetConvention()
            allowEmptyFiles = true
        }
    }

    def discordContent = changelogText.length() > 4000 ? "Changelog is too long, check it on Modrinth." : changelogText

    discord {
        webhookUrl = providers.environmentVariable("DISCORD_WEBHOOK")
        dryRunWebhookUrl = providers.environmentVariable("DISCORD_WEBHOOK_DRY_RUN")
        content = """
                # $mod_name | $mod_version

                $discordContent
            """.stripIndent()

        style {
            link = "BUTTON"
            look = "MODERN"
            thumbnailUrl = "https://cdn.modrinth.com/data/BHovO9FP/6beaca9c4801541c8346e5cca783116cb953649b.gif"
            color = "curseforge"

        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from(components.java)
        }
    }
    repositories {
        maven {
            name = 'igleeRepo'
            url = providers.gradleProperty("publish_maven_repository_url").orNull
            credentials {
                username = providers.environmentVariable("MAVEN_USERNAME").orNull
                password = providers.environmentVariable("MAVEN_PASSWORD").orNull
            }
            authentication {
                basic(BasicAuthentication)
            }
        }
    }
}


String calculateGitHash() {
    try {
        ExecOutput output = providers.exec {
            commandLine("git", "rev-parse", "HEAD")
        }
        return output.standardOutput.asText.get().trim()
    } catch (Throwable ignored) {
        return "unknown"
    }
}
