org.gradle.jvmargs=-Xmx4096M
org.gradle.daemon=false

minecraft_version=1.21.1
minecraft_version_range=[1.21,)
neo_version=21.1.219
neo_version_range=[21,)
loader_version_range=[2,)

## Mod Properties
mod_id=resourcefulshulkers
mod_name=Resourceful Shulkers
mod_license=MIT
mod_version=1.0.0-beta
mod_group_id=fr.iglee42
mod_authors=iglee42
mod_description=Generate resources with shulkers

lib_version=1.2.7
lib_version_range=[1.2.7,)
jei_version=19.25.0.322
