package fr.iglee42.resourcefulshulkers.config;

import fr.iglee42.resourcefulshulkers.aura.AuraOverlay;
import net.minecraft.world.item.ItemStack;
import net.neoforged.neoforge.common.ModConfigSpec;
import net.neoforged.neoforge.common.ModConfigSpec.*;

public class RSServerConfig {
    public static final Builder BUILDER = new Builder();
    public static final ModConfigSpec SPEC;

    public static final IntValue MAX_AURA;

    public static final BooleanValue ACCELERATION_PROTECTION;

    public static final IntValue ABSORBER_DURATION;
    public static final IntValue ABSORBER_AURA;

    public static final IntValue TARGET_RADIUS;

    public static final IntValue INFUSER_DURATION;
    public static final IntValue INFUSER_NO_AI_AURA;

    public static final IntValue BOX_MAX_DURABILITY;
    public static final IntValue BOX_MAX_PROGRESS;
    public static final IntValue BOX_BASE_AMOUNT;
    public static final IntValue BOX_SHELL_DURABILITY;

    public static final IntValue TRAINER_MAX_PROGRESS;
    public static final IntValue TRAINER_BASE_AMOUNT;

    public static final DoubleValue QUANTITY_MULTIPLIER;
    public static final DoubleValue SHELL_MULTIPLIER;
    public static final DoubleValue DURABILITY_REDUCTION;


    static {
        BUILDER.push("general");
        ACCELERATION_PROTECTION = BUILDER.comment("If true, boxes and multiblocks will be protected from acceleration item like the Time in a Bottle or the Temporal pouch").define("acceleration_protection", true);
        BUILDER.pop();

        BUILDER.push("aura");
        MAX_AURA = BUILDER.comment("The maximum amount of aura a chunk can store").defineInRange("max_aura", 262_144, 1, Integer.MAX_VALUE);
        BUILDER.pop();

        BUILDER.push("shulker_absorber");
        ABSORBER_DURATION = BUILDER.comment("The duration (in seconds) that it takes a shulker absorber to work").defineInRange("absorber_duration", 32, 1, Integer.MAX_VALUE);
        ABSORBER_AURA = BUILDER.comment("The amount of aura given by a shulker when placed on a absorber").defineInRange("absorber_aura", 4096, 1, Integer.MAX_VALUE);
        BUILDER.pop();

        BUILDER.push("shulkers");
        TARGET_RADIUS = BUILDER.comment("The radius (in blocks) within which shulkers will search Purpur Target").defineInRange("target_radius", 8, 1, 64);
        BUILDER.pop();

        BUILDER.push("shulker_infuser");
        INFUSER_DURATION = BUILDER.comment("The duration of an infusion recipe").defineInRange("default_duration", 200, 1, Integer.MAX_VALUE);
        INFUSER_NO_AI_AURA = BUILDER.comment("The amount of aura consumed by a shulker infuser to keep an entity without AI and silent (Set to -1 to disable this behaviour)").defineInRange("no_ai_aura", 100, -1, Integer.MAX_VALUE);
        BUILDER.pop();

        BUILDER.push("generating_boxes").comment("Theses configs applies to generating and also to end cities");
        BOX_MAX_DURABILITY = BUILDER.comment("Max durability of a generating box").defineInRange("max_durability", 256, 1, Integer.MAX_VALUE);
        BOX_MAX_PROGRESS = BUILDER.comment("The number of ticks required for a box to generate an item").defineInRange("max_progress", 100, 1, Integer.MAX_VALUE);
        BOX_BASE_AMOUNT = BUILDER.comment("The amount of items generated by a box without upgrade").defineInRange("item_amount", 1, 1, 64);
        BOX_SHELL_DURABILITY = BUILDER.comment("The durability restored to a box by a shulker shell").defineInRange("shell_durability", 4, 1, Integer.MAX_VALUE);
        BUILDER.pop();

        BUILDER.push("trainer").comment("Theses configs applies to shulker trainer");
        TRAINER_MAX_PROGRESS = BUILDER.comment("The number of ticks required for a shulker in the trainer to generate a shell").defineInRange("max_progress", 200, 1, Integer.MAX_VALUE);
        TRAINER_BASE_AMOUNT = BUILDER.comment("The amount of shells generated by a shulker in the trainer without upgrade").defineInRange("item_amount", 1, 1, 64);
        BUILDER.pop();

        BUILDER.push("upgrades");
        QUANTITY_MULTIPLIER = BUILDER.comment("The multiplier applied to the amount of items generated by a box when upgraded").comment("The amount of items generated is defined by the formula : base_amount + (nb_upgrade * multiplier)").defineInRange("quantity_multiplier", 2, 1, Double.MAX_VALUE);
        SHELL_MULTIPLIER = BUILDER.comment("The multiplier applied to the amount of durability restored by a shulker shell when the box is upgraded").comment("The durability restored is defined by the formula : shell_base_durability * (1 + nb_upgrade * multiplier)").defineInRange("shell_multiplier", 0.5, 0, Double.MAX_VALUE);
        DURABILITY_REDUCTION = BUILDER.comment("The reduction of durability per durability upgrade in a box (E.g. if this is set to 0.2, the durability lose chance is reduce by 20%)").defineInRange("durability_reduction", 0.2, 0, 1);
        BUILDER.pop();

        SPEC = BUILDER.build();
    }

    public static int getMaxDurability(){
        return BOX_MAX_DURABILITY.get();
    }

    public static int getMaxAura(){
        return SPEC.isLoaded() ? MAX_AURA.get() : MAX_AURA.getDefault();
    }
}
